site2/account/urls.py
from django.urls import path
from . import views

app_name = 'account' 

urlpatterns = [
    path('register/' , views.UserRegisterView.as_view() , name = 'user_register'),
    path('login/' , views.UserLoginView.as_view() , name = 'user_login'),

    path('logout/' , views.UserLogoutView.as_view() , name ='user_logout'),
    path('profile/<int:user_id>/' , views.UserProfileView.as_view() , name = 'user_profile'),

    path('reset/' , views.UserPasswordResetView.as_view() , name='reset_password'),
    path('reset/done/' , views.UserPasswordResetDoneView.as_view() , name='password_reset_done'),

    path('confirm/<uidb64>/<token>/' , views.UserPasswordResetConfirmView.as_view() , name='password_reset_confirm'),
    path('confirm/complete/' , views.UserPasswordResetCompleteView.as_view() , name='password_reset_complete'),

    path('follow/<int:user_id>/' , views.UserFollowView.as_view() , name='user_follow'),
    path('unfollow/<int:user_id>/' , views.UserUnfollowView.as_view() , name='user_unfollow'),

    path('edit_user/' , views.EditUserView.as_view() , name='edit_user'),
    

]

site2/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('' , views.HomeView.as_view() , name = 'home'),
]

site2/site2/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('' , include('post.urls' , namespace='post')),
    path('account/' , include('account.urls' , namespace='account')),
]

site2/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

site2/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav">
      {% if not request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
        <a class="nav-link active" href="{% url 'account:user_register' %}">Register</a>
        <a class="nav-link active" href="{% url 'account:user_login' %}">Login</a>
      {% else %}
        <a class="nav-link active" href="{% url 'home:home' %}">Home &nbsp&nbsp|</a>
        <a class="nav-link active" href="{% url 'account:user_profile' request.user.id %}">Profle &nbsp&nbsp&nbsp|</a>
        <a class="nav-link active" href="{% url 'account:user_logout' %}">Logout &nbsp&nbsp&nbsp|</a>
        {% comment %} <li class="nav-link active" style = "position:relative; left:890px"; href="#"><h6>Your are logged in as {{ user.username }}</h6></li> {% endcomment %}
        {% if request.user.id == user.id %}
          <li class="nav-link active" style = "position:relative; left:870px"; href="#"><h6>Your are logged in as {{ user.username }}</h6></li>

        {% else %}
          <li class="nav-link active" style = "position:relative; left:870px"; href="#"><h6>Your are logged in as {{ request.user.username }}</h6></li>
        {% endif %}

      {% endif %}

    </div>
  </div>
</nav>